# Documentation
# * mdbook   https://rust-lang.github.io/mdBook/
# * template https://github.com/kg4zow/mdbook-template/

[book]
authors             = ["Data Intelligence Team"]
language            = "en"
multilingual        = false
src                 = "doc"
title               = "DD-Ranking API Documentation"

[output.html]
mathjax-support = true